# Generated by Django 4.0.4 on 2022-05-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_alter_issue_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='host',
            field=models.CharField(default=' ', max_length=50, unique=True),
        ),
    ]
