# Generated by Django 4.0.4 on 2022-05-26 19:08

from django.db import migrations, models
import issues.models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='host',
            field=models.CharField(default=issues.models.generate_unique_code, max_length=50, unique=True),
        ),
    ]
