# Generated by Django 4.0.4 on 2022-05-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='host',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
